deploy-master:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker image build --build-arg "gitlab_user=${GITLAB_USER}" --build-arg "gitlab_token=${GITLAB_TOKEN}" --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master


deploy-tags:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker image build --build-arg "gitlab_user=${GITLAB_USER}" --build-arg "gitlab_token=${GITLAB_TOKEN}" --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags
